# Generated by Django 4.0 on 2021-12-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('identificacion', models.IntegerField()),
                ('staff', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
    ]
