# Generated by Django 4.0 on 2021-12-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_turnos_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.usuario'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='estado',
            field=models.CharField(choices=[('p', 'pendiente'), ('a', 'activo'), ('f', 'finalizado')], default='p', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='staff',
            field=models.CharField(choices=[('s', 'si'), ('n', 'no')], default='n', max_length=100),
        ),
    ]
