# Generated by Django 4.0 on 2021-12-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_turnos_usuario_alter_turnos_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='usuarioEditor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
