# Generated by Django 4.0 on 2021-12-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_turnos_usuarioeditor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
    ]
